name: FinanceMate
options:
  bundleIdPrefix: com.products
  deploymentTarget:
    macOS: "13.0"
targets:
  FinanceMate:
    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.products.FinanceMate
        INFOPLIST_FILE: Resources/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        DEVELOPMENT_TEAM: 7KV34995HH
        CODE_SIGN_STYLE: Automatic
        SIGNING_CERTIFICATE: "Development"
        APP_CATEGORY: Productivity
        VERSION: 0.1
        BUILD: 1
