# SwiftLint Configuration for FinanceMate
# Professional macOS Application Standards - AUDIT-2024JUL02-MACOS-BASELINE
# Version: 1.0 | Compatible with SwiftLint 0.59.1

# Included/Excluded Paths
included:
  - _macOS/FinanceMate-Sandbox/FinanceMate
  - _macOS/FinanceMate/FinanceMate

excluded:
  - _macOS/FinanceMate-Sandbox/FinanceMateTests/_QUARANTINED
  - _macOS/FinanceMate/FinanceMateTests/_QUARANTINED
  - temp/
  - build/
  - .build/
  - DerivedData/
  - _macOS/FinanceMate-Sandbox/FinanceMate.xcodeproj
  - _macOS/FinanceMate/FinanceMate.xcodeproj

# Analyzer Rules (Advanced Static Analysis)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Only enable specific rules for professional standards
only_rules:
  # Code Structure & Organization
  - file_length
  - type_body_length
  - function_body_length
  - line_length
  - cyclomatic_complexity
  - nesting
  
  # Naming Conventions
  - type_name
  - identifier_name
  - generic_type_name
  
  # Code Quality
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - weak_delegate
  - large_tuple
  - redundant_optional_initialization
  - unused_optional_binding
  
  # Swift Best Practices
  - trailing_whitespace
  - trailing_newline
  - leading_whitespace
  - vertical_whitespace
  - empty_parameters
  - return_arrow_whitespace
  - operator_whitespace
  - comma
  - colon
  
  # Control Flow
  - control_statement
  - empty_enum_arguments
  - syntactic_sugar
  - redundant_type_annotation
  - redundant_void_return
  
  # Documentation & Comments
  - comment_spacing
  - empty_count
  - todo
  - mark
  
  # Advanced Quality Rules
  - duplicate_imports
  - orphaned_doc_comment
  - private_over_fileprivate
  - unneeded_break_in_switch
  - vertical_parameter_alignment
  - closure_parameter_position
  - multiline_function_chains
  - multiline_parameters
  - multiple_closures_with_trailing_closure

# Rule Configurations
file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

type_body_length:
  warning: 200
  error: 300

function_body_length:
  warning: 40
  error: 60

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

cyclomatic_complexity:
  warning: 8
  error: 12

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 4
    error: 5

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - T
    - K
    - V

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z
    - to
    - at
    - in
    - of
    - on
    - or
    - up

large_tuple:
  warning: 3
  error: 4

# Custom Rules for FinanceMate
custom_rules:
  # Ensure proper error handling in financial operations
  financial_error_handling:
    name: "Financial Error Handling"
    regex: "(calculateTotal|processTransaction|validateAmount)\\s*\\([^)]*\\)\\s*(?!.*(?:throws|Result|Optional))"
    message: "Financial operations must have explicit error handling"
    severity: warning
  
  # Ensure proper logging in sensitive operations
  sensitive_operation_logging:
    name: "Sensitive Operation Logging"
    regex: "(signIn|authenticate|decrypt|keychain).*(?!.*(?:log|print|debug))"
    message: "Sensitive operations should include appropriate logging"
    severity: warning
  
  # Ensure glassmorphism theme usage
  theme_compliance:
    name: "Theme Compliance"
    regex: "\\.background\\(Color\\.[a-zA-Z]+\\)"
    message: "Use CentralizedTheme colors instead of hardcoded Color values"
    severity: warning
  
  # Prevent hardcoded strings in user-facing text
  localization_ready:
    name: "Localization Ready"
    regex: "Text\\(\"[^\"]+\"\\)"
    message: "Use localized strings for user-facing text"
    severity: warning
    
  # Ensure proper accessibility identifiers
  accessibility_identifiers:
    name: "Accessibility Identifiers"
    regex: "Button\\(|TextField\\(|Image\\("
    message: "Interactive elements should have accessibility identifiers"
    severity: warning

# Reporter Configuration
reporter: "xcode"