# SwiftLint Configuration for FinanceMate
# Enhanced code quality enforcement with SweetPad integration

# Paths to include during linting
included:
  - FinanceMate/
  - FinanceMate-Sandbox/
  - FinanceMateTests/
  - FinanceMateUITests/

# Paths to exclude during linting
excluded:
  - build/
  - DerivedData/
  - .build/
  - Pods/
  - Carthage/
  - xcuserdata/
  - temp/

# Disable specific rules
disabled_rules:
  - trailing_whitespace
  - todo
  - line_length # Handled by custom rule below

# Enable opt-in rules for advanced quality
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_space_in_method_call
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10

# Naming conventions
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - db
    - i
    - j
    - k
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# Custom rules for FinanceMate project
custom_rules:
  # Enforce MVVM pattern compliance
  viewmodel_naming:
    name: "ViewModel Naming Convention"
    regex: '(class|struct)\s+\w*ViewModel\s*[:{\s]'
    match_kinds:
      - identifier
    message: "ViewModels should end with 'ViewModel'"
    severity: warning

  # Enforce glassmorphism modifier usage
  glassmorphism_consistency:
    name: "Glassmorphism Consistency"
    regex: '\.background\(Color\.'
    message: "Use .modifier(GlassmorphismModifier(.style)) instead of direct background colors"
    severity: warning

  # Ensure Australian locale compliance
  currency_formatting:
    name: "Australian Currency Formatting"
    regex: 'NumberFormatter\(\)'
    message: "Use CurrencyFormatter.australian for currency formatting"
    severity: error

  # Enforce Core Data best practices
  coredata_context:
    name: "Core Data Context Usage"
    regex: 'NSManagedObjectContext\(\)'
    message: "Use PersistenceController.shared.container.viewContext"
    severity: warning

  # Security compliance
  hardcoded_secrets:
    name: "No Hardcoded Secrets"
    regex: '(password|secret|key|token)\s*=\s*"[^"]*"'
    message: "Do not hardcode secrets. Use Keychain or environment variables."
    severity: error

# Reporter configuration
reporter: "xcode"

# Enable automatic correction where possible
autocorrect: true

# Strict mode for CI/CD
strict: false

# Cache path for performance
cache_path: ".swiftlint_cache/"