# SwiftLint Configuration for FinanceMate
# Version: 1.0.0
# Created for comprehensive code quality enforcement

# Directories to include
included:
  - FinanceMate
  - FinanceMateTests
  - FinanceMateUITests

# Directories to exclude
excluded:
  - Carthage
  - Pods
  - .build
  - Resources
  - test_artifacts
  - Scripts

# Disabled rules (only for genuine technical reasons)
disabled_rules:
  - trailing_whitespace  # Will be auto-fixed by formatter
  - duplicate_imports    # Will be manually fixed during cleanup

# Enabled rules (critical for build stability)
opt_in_rules:
  - force_try
  - implicit_getter
  - redundant_string_enum_value
  - redundant_type_annotation
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

# Rule configurations
identifier_name:
  min_length: 2  # Allow short names like 'id', 'x', 'y'
  max_length: 60
  excluded:
    - r    # RGB red component
    - g    # RGB green component  
    - b    # RGB blue component
    - x    # x coordinate
    - y    # y coordinate
    - i    # index
    - id   # identifier

line_length:
  warning: 120
  error: 150  # STRICT STANDARD RESTORED
  ignores_urls: true
  ignores_comments: true

file_length:
  warning: 400
  error: 600  # STRICT STANDARD RESTORED

function_body_length:
  warning: 50
  error: 100  # STRICT STANDARD RESTORED

type_body_length:
  warning: 200
  error: 300  # STRICT STANDARD RESTORED

cyclomatic_complexity:
  warning: 10
  error: 15  # STRICT STANDARD RESTORED

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 10

# Force try configuration  
force_try:
  severity: error

# Custom rules for specific patterns
custom_rules:
  # Prevent hardcoded authentication bypass
  no_hardcoded_auth:
    name: "No Hardcoded Authentication"
    regex: 'isAuthenticated\s*=\s*true'
    message: "Don't hardcode authentication bypass"
    severity: error
    
  # Ensure proper error handling
  proper_error_handling:
    name: "Proper Error Handling"
    regex: 'try!\s'
    message: "Use proper error handling instead of try!"
    severity: error
    
  # Prevent empty catch blocks
  no_empty_catch:
    name: "No Empty Catch Blocks"
    regex: 'catch\s*\{\s*\}'
    message: "Catch blocks should not be empty"
    severity: warning

# Reporting configuration
reporter: "emoji" # xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging

# Performance settings
# compilation_mode: wholemodule # Removed - invalid configuration