#!/bin/bash

echo "🍎 Apple Sign-In Configuration Script"
echo "======================================"
echo ""

# Current configuration
BUNDLE_ID="com.ablankcanvas.financemate"
TEAM_ID="7KV34995HH"

echo "📋 Current Configuration:"
echo "   Bundle ID: $BUNDLE_ID"
echo "   Team ID: $TEAM_ID"
echo ""

echo "🔧 CRITICAL: Apple Sign-In Configuration Required"
echo ""
echo "The Apple Sign-In error occurs because the App ID is not properly"
echo "configured in Apple Developer Portal with Sign In with Apple capability."
echo ""

echo "📱 IMMEDIATE FIX REQUIRED:"
echo ""
echo "1. Go to: https://developer.apple.com/account/"
echo "2. Sign in with Apple ID associated with Team ID: 7KV34995HH"
echo "3. Navigate to: Certificates, Identifiers & Profiles"
echo "4. Click: Identifiers"
echo ""

echo "5. CREATE OR UPDATE APP ID:"
echo "   - If '$BUNDLE_ID' exists:"
echo "     • Click on it → Edit → Capabilities"
echo "     • Enable 'Sign In with Apple'"
echo "     • Configure as 'Enable as Primary App ID'"
echo "     • Save"
echo ""
echo "   - If '$BUNDLE_ID' does NOT exist:"
echo "     • Click '+' to create new App ID"
echo "     • Description: FinanceMate"
echo "     • Bundle ID: Explicit → $BUNDLE_ID"
echo "     • Capabilities: Enable 'Sign In with Apple'"
echo "     • Configure as 'Enable as Primary App ID'"
echo "     • Register"
echo ""

echo "6. UPDATE PROVISIONING PROFILE:"
echo "   - Navigate to: Profiles"
echo "   - Find profile for FinanceMate (if exists) or create new one"
echo "   - Type: macOS App Development"
echo "   - App ID: Select the updated $BUNDLE_ID"
echo "   - Certificates: Select your development certificate"
echo "   - Generate and Download"
echo ""

echo "7. INSTALL IN XCODE:"
echo "   - Double-click downloaded provisioning profile"
echo "   - OR: Xcode → Preferences → Accounts → Download Manual Profiles"
echo ""

echo "🧪 TESTING AFTER CONFIGURATION:"
echo ""
echo "After completing the above steps:"
echo "1. Clean Build (⌘+Shift+K)"
echo "2. Build and Run"
echo "3. Test Apple Sign-In (should work without error)"
echo "4. Test Google Sign-In (should continue working)"
echo ""

echo "⚠️  IMPORTANT NOTES:"
echo ""
echo "• This configuration is required ONCE per Bundle ID"
echo "• Changes take 10-15 minutes to propagate"
echo "• You MUST have Apple Developer Program membership"
echo "• Team ID 7KV34995HH must have admin privileges"
echo ""

echo "🎯 SUCCESS CRITERIA:"
echo "• Apple Sign-In works without error messages"
echo "• Both Apple and Google authentication functional" 
echo "• Professional user experience maintained"
echo ""

echo "📞 SUPPORT:"
echo "If you encounter issues:"
echo "• Verify Apple Developer Program membership is active"
echo "• Ensure Bundle ID matches exactly: $BUNDLE_ID"
echo "• Wait 15 minutes after changes before testing"
echo "• Check Xcode signing settings match Team ID: $TEAM_ID"