#!/bin/bash

echo "🔍 Apple Sign-In Capability Verification"
echo "========================================"
echo ""

BUNDLE_ID="com.ablankcanvas.financemate"
TEAM_ID="7KV34995HH"

echo "📋 Configuration Status:"
echo "   Bundle ID: $BUNDLE_ID ✅ (Already exists)"
echo "   Team ID: $TEAM_ID ✅ (Valid)"
echo ""

echo "🚨 LIKELY ISSUE: Sign In with Apple capability not enabled"
echo ""
echo "Since the Bundle ID already exists, the issue is most likely that"
echo "the 'Sign In with Apple' capability is not enabled for this App ID."
echo ""

echo "🔧 SPECIFIC FIX REQUIRED:"
echo ""
echo "1. Go to: https://developer.apple.com/account/"
echo "2. Navigate to: Certificates, Identifiers & Profiles → Identifiers"
echo "3. Find and click: 'com.ablankcanvas.financemate'"
echo ""
echo "4. CHECK CAPABILITIES SECTION:"
echo "   Look for 'Sign In with Apple' in the capabilities list"
echo ""
echo "   ❌ If NOT enabled:"
echo "   • Check the 'Sign In with Apple' checkbox"
echo "   • Select 'Enable as Primary App ID'"
echo "   • Click 'Save' at the top right"
echo ""
echo "   ✅ If already enabled:"
echo "   • The issue may be provisioning profile"
echo "   • Continue to step 5"
echo ""

echo "5. UPDATE PROVISIONING PROFILE:"
echo "   - Navigate to: Profiles"
echo "   - Look for profile containing '$BUNDLE_ID'"
echo "   - If found: Click 'Edit' → Regenerate → Download"
echo "   - If not found: Create new macOS Development profile"
echo "     • Name: FinanceMate Development"
echo "     • Type: macOS App Development"
echo "     • App ID: com.ablankcanvas.financemate"
echo "     • Certificates: Select your certificate"
echo "     • Devices: Select your Mac"
echo "     • Generate → Download"
echo ""

echo "6. INSTALL PROVISIONING PROFILE:"
echo "   - Double-click the downloaded .provisionprofile file"
echo "   - OR: Open Xcode → Preferences → Accounts → Download Manual Profiles"
echo ""

echo "7. VERIFY IN XCODE:"
echo "   - Open FinanceMate.xcodeproj"
echo "   - Select FinanceMate target"
echo "   - Go to 'Signing & Capabilities' tab"
echo "   - Verify:"
echo "     • Team: BERNHARD JOSHUA BUDIONO (7KV34995HH)"
echo "     • Bundle Identifier: com.ablankcanvas.financemate"
echo "     • Provisioning Profile: Automatic (or select manual profile)"
echo "     • Capabilities: 'Sign In with Apple' should be listed"
echo ""

echo "🧪 TESTING STEPS:"
echo ""
echo "After configuration:"
echo "1. Clean Build (⌘+Shift+K)"
echo "2. Build and Run"
echo "3. Test Apple Sign-In → Should work without error"
echo "4. Test Google Sign-In → Should continue working"
echo ""

echo "⚡ QUICK VERIFICATION:"
echo ""
echo "To verify the capability is enabled, check in Apple Developer Portal:"
echo "• Go to Identifiers → com.ablankcanvas.financemate"
echo "• Scroll down to 'Capabilities' section"
echo "• Look for 'Sign In with Apple' with blue checkmark"
echo ""
echo "If you see 'Sign In with Apple ✅ Enabled', then the issue is"
echo "likely the provisioning profile needs to be regenerated."
echo ""

echo "🎯 SUCCESS INDICATORS:"
echo "• No error message when tapping Apple Sign-In"
echo "• Apple authentication flow appears normally"
echo "• Both authentication methods work seamlessly"
echo ""

echo "📞 If this doesn't resolve the issue:"
echo "• Check that Apple Developer Program membership is active"
echo "• Verify you have admin access to Team ID 7KV34995HH"
echo "• Wait 10-15 minutes after making changes before testing"