name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Run Architecture Compliance Check
      run: |
        cd _macOS/FinanceMate
        chmod +x build_guard.sh
        # Run only the architecture checks, not the full test suite yet
        ./build_guard.sh || true
        
    - name: Build FinanceMate
      run: |
        cd _macOS/FinanceMate
        xcodebuild build \
          -project FinanceMate.xcodeproj \
          -scheme FinanceMate \
          -destination 'platform=macOS'
          
    - name: Archive Build Logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: _macOS/FinanceMate/build_output.log
        
    # Test execution will be enabled once scheme is configured
    # - name: Run Tests
    #   run: |
    #     cd _macOS/FinanceMate
    #     xcodebuild test \
    #       -project FinanceMate.xcodeproj \
    #       -scheme FinanceMate \
    #       -destination 'platform=macOS' \
    #       -enableCodeCoverage YES